{% set name = "tableschema-sql" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0b3fc072ddc1e0cc718891d3a5b3a22ce252e19d1d5b81b634c5f3f859aea4c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.9
    - sqlalchemy >=1.0
    - pybloom_live >=2.2
    - tabulator >=1.0.0a5
    - tableschema >=1.0

test:
  imports:
    - tableschema_sql

about:
  home: http://github.com/frictionlessdata/tableschema-sql-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Generate and load SQL tables based on Table Schema descriptors.'

extra:
  recipe-maintainers:
    - roll
