travis:
  secure:
    BINSTAR_TOKEN: HwcxzomCaDF7dFm+XuRboVnyEE0uVLxY48eu0Di5+7alJisErZwDw1vR/KXd2+KXCaARvVWJehMJa/zRxT0z68gkPuaBZr7EhWq9oEmIpXkppikv7WtmEBQICvAcDmHWlxz0xo6FE6FWqPctTEEveg2ucVAWyzMEbp6qbfvx6bSUDmBDHVlW+bSLbUXphZGZWOLof8mjWvV5pF4U1CwCF6pqJTNprry62RwAWd4QfgE8M/7dtf4YuT6x9phh8c0j7qr+T7xBXB+L/2x1mBvsI8xnzoQEIHQuaS6XUs9yB4D3Eggb4cDy4AxOF/RNgMuQ3gGraSi9DcMj8kzwUzf+5jpzbWxeOKLtcy6/5Gc76M6eVI6lKFu3siXdqgSoJ4HLEwcLUJk9SiVzu7geVF19lueTtdF204psyR6QxV6Plx/r1k0czSA68+TNNc0wxGeOnmyQnJhp6zMqUn8yyg0BqaZxErBXHKx5zY/tLGPMin+TYJY7fbBm82FRbhw8KxZwuvE4XHN3SDzlaXQQOtNM8movHvBp3TTfDiiVSTTsSse7uvdSC9zLAsidODV+GbPOe7aaLm1pWwSvZd62DfJBEwWmwBmqVscMv3aL+y/mU7u4s1aZCahG1PsHaZUy0dTPtbsyGmWAmcxpqx6j8SvX6Y0++WdEvNev+oiXkZgYgp4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
